### ISSUE TITLE
Support Model upconv_7/photo

### ISSUE THREAD

**Issue by vongocminh778** [z3lx/waifu2x-tensorrt#2]
Your program runs quite well on windows. Thank you! I wonder if you support running model upconv_7/photo?

**Comment by z3lx** [comment]
I believe the inputs and output of that model is the same as the others supported in the project. You just have to modify [`main.cpp`](https://github.com/z3lx/waifu2x-tensorrt/blob/4f8ee4e21f5909ecc873b5e4221eeb8b4ef8ffed/src/main.cpp#L26) file at line 26 to add that model name, and it should work.

**Comment by vongocminh778** [comment]
Thanks. I have solved the problem!
